repos:
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt
        args: ["-i", "2", "-ci"]

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.20.0 # Use the latest tag
    hooks:
      - id: stylua-github